### ISSUE TITLE
Upgrade package_info_plus : ^4.0.2

### ISSUE THREAD

**Issue by ArivhaySoft** [Floating-Dartists/matomo-tracker#111]
../../../../.pub-cache/hosted/pub.dev/package_info_plus-3.0.2/lib/src/file_version_info.dart:13:17: Error: Field 'wLanguage' cannot be nullable or have type 'Null', it must be `int`, `double`, `Pointer`, or a subtype of `Struct` or `Union`.
  external int? wLanguage;

**Comment by TesteurManiak** [comment]
I close this as it is already upgraded on the `dev` branch.
