### ISSUE TITLE
no MatomoTracker.matomoObserver,

### ISSUE THREAD

**Issue by OpenSphereSoftware** [Floating-Dartists/matomo-tracker#117]
**Describe the bug**
In your migration guide on pub.dev you write for 4.0.0 that we have to set the MatomoTracker.matomoObserver,
But it is not existing :D 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by TesteurManiak** [comment]
The example project is quite explicit https://github.com/Floating-Dartists/matomo-tracker/blob/main/example/lib/main.dart#L45
