### ISSUE TITLE
Modify url after initialization

### ISSUE THREAD

**Issue by ahmdt** [Floating-Dartists/matomo-tracker#119]
Hi, is there a way to modify the url after initialization?
China's Firewall  slows down the traffic to our default domain and because of that we need a proxy.
User can activate  the proxy in the app settings. 

In the current approach we are calling dispose() but it's still locked with the message "`MatomoTracker has already been initialized. You can check the initialize property to see if it has been initialized.`"

```dart
await MatomoTracker.instance.initialize(
  siteId: 11,
  url: 'https://analyctics.com',
);
MatomoTracker.instance.pause();
MatomoTracker.instance.dispose();
await MatomoTracker.instance.initialize(
  siteId: 11,
  url: 'https://china-analyctics.cn',
);
```

**Comment by TesteurManiak** [comment]
Unfortunately, it is not possible.
This is a feature that will need some investigations as it would imply quite a bit of refactoring to change the url on the fly. We could also consider modifying the `dispose` method to reset the initialization state.

**Comment by OgnenDreamix** [comment]
@TesteurManiak any chance that we can publish this as 4.1.0 on pub.dev? Thank you

**Comment by TesteurManiak** [comment]
Sure! I'll publish it asap.
