### ISSUE TITLE
How to set matomoObserver in MaterialApp.router

### ISSUE THREAD

**Issue by Adahn** [Floating-Dartists/matomo-tracker#121]
**Describe the bug**

Hi,
I am starting with Flutter currently and try to connect the Matomo Analytics to my app. 

The documentation recommends to set the matomoObserver in the navigatorObserver in the MaterialApp : 

```
MaterialApp(
    // ...
    navigatorObservers: [
        matomoObserver,
    ],
);
```

In my Flutter application I am not using MaterialApp but MaterialApp.router(..) which does not have the navigatorObservers keyword and uses the auto_route package.

```
import 'package:auto_route/auto_route.dart';

final _appRouter = AppRouter();
MaterialApp.router(
                title: 'Flutter Demo',
                ... 
                routerConfig: _appRouter.config(),
            );
```

Is there a way to set the matomoObserver in the MaterialApp.router(...) ?

Thanks in advance!

Flutter version: 3.13.2
Dart: 3.1.9
DevTools: 2.25.0

**Comment by TesteurManiak** [comment]
If I'm refering to [auto_route documentation](https://pub.dev/packages/auto_route#navigation-observers) your generated router should have a `config` method where you can specify a `navigatorObservers` callback:
```dart
return MaterialApp.router(
  routerConfig: _appRouter.config(
    navigatorObservers: () => [matomoObserver],
  ),
);
```
I'm closing this as it is not an issue with the package in itself.
