### ISSUE TITLE
Feat: Change `siteId` to a `String` type

### ISSUE THREAD

**Issue by jainhitesh9998** [Floating-Dartists/matomo-tracker#129]
**Describe the bug**

Configuring Matomo-ProtectTrackID enables us to use hash instead of int as part of site-id.
 Changing the datatype of  siteid from in to  String has no affect on the functionality, but improves the compatibility with the ProtectTrackID library as the site id generated then are string.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jainhitesh9998** [comment]
we have tested it with our setup, can raise a PR for the same.

**Comment by TesteurManiak** [comment]
Sure! I don't see any problem with changing `MatomoTracker.siteId` to a `String` type. You can open a PR for review, otherwise I'll make the changes after my vacations.

**Comment by ken717w** [comment]
Just upgraded from 4.x to 5.0 and found this breaking change. This should be mentioned in the upgrade guide.

**Comment by TesteurManiak** [comment]
@ken717w Documentation has been updated
