### ISSUE TITLE
Add opt-in possibility

### ISSUE THREAD

**Issue by nietsmmar** [Floating-Dartists/matomo-tracker#134]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
I'd like to have a method to get the information if my current MatomoTracker.instance is opted in or out. And respectively offer my users a possibility to either opt-in or opt-out. (That is how I currently have it in wordpress with matomo connect) Currently only opting out is possible.

**Describe alternatives you've considered**
Only offer an opt-out button. But I can't even check the current status after page refresh.

**Keep up the good work! Thanks for this great package.**

**Comment by TesteurManiak** [comment]
You already have the `MatomoTracker.instance.optOut` getter and the `MatomoTracker.instance.setOptOut(optOut: true)` method.
Is this not enough?

**Comment by nietsmmar** [comment]
@TesteurManiak Oh I somehow didn't find the getter. Sorry. I guess this can be closed then.
