### ISSUE TITLE
Page URLs get encoded

### ISSUE THREAD

**Issue by ken717w** [Floating-Dartists/matomo-tracker#147]
**Describe the bug**
We have a website and a Flutter app using this library running, both of them connected to the same Matomo instance. Our URLs could contain Chinese character, e.g. `https://www.example.com/主頁`.

In web traffics it works perfectly, while in the app traffic we collected via this library the URL becomes `https://www.example.com/%E4%B8%BB%E9%A0%81`. This way we're not able to include the record in our report which using segmentation `pageUrl=@主頁`.

**Comment by TesteurManiak** [comment]
It's because Dart `Uri` class will automatically encode non-ASCII characters, and we are using `Uri` to parse and encode query parameters.
The only solution that I see would be to only manipulate the URL using strings but this is some heavy work to do and might cause regressions.
