### ISSUE TITLE
Update device_info_plus and package_info_plus

### ISSUE THREAD

**Issue by PavlyukovYegor** [Floating-Dartists/matomo-tracker#149]
Hi guys, I'm using your library for a production project, could you please update package_info_plus to at least 6.0.0 and device_info_plus to at least 10.0.1? Because it was in these versions that the developers added privacy policy to iOS, without which Apple will reject builds from May

https://developer.apple.com/support/third-party-SDK-requirements/

**Comment by TesteurManiak** [comment]
I've published the latest dependency bump in a version [`5.0.0-dev.2`](https://pub.dev/packages/matomo_tracker/versions/5.0.0-dev.2) on pub.dev, this should solve your issue.
Note that for the future if you need a quick dependency bump you can target the `main` git branch in your pubspec, we're bumping automatically the dependencies once a week with dependabot.

**Comment by PavlyukovYegor** [comment]
Thanks
