### ISSUE TITLE
Invalid requests to self-hosted Matomo 5.0.1

### ISSUE THREAD

**Issue by kuhnroyal** [Floating-Dartists/matomo-tracker#155]
**Describe the bug**
I am trying to migrate from `matomo_forever` package which doesn't seem to be forever.

When the request is sent, the received response for the batch is a success but the individual request are invalid.
I understand that the main issue is probably me doing something wrong or the instance being miss-configured.

```
{
	"status": "success",
	"tracked: 0,
	"invalid": 3
}
```
Should this case actually be an error or at least a warning log?

**To Reproduce**
No idea

**Expected behavior**
```
{
	"status": "success",
	"tracked: 3,
	"invalid": 0
}
```

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro Max
 - OS: iOS 17.5.1

**Comment by TesteurManiak** [comment]
Have you tried with a simpler project to check with more basic events to see if they are handled properly?
Are you using a self hosted instance of matomo?
Despite the response do you have the event send displayed?

**Comment by kuhnroyal** [comment]
They are pretty basic, just navigation, I removed all dimensions.
This is a self-hosted 5.0.1 instance, don't have access to logs atm.
The events are not being displayed.

```json
{"requests":["?idsite=14&rec=1&action_name=%2Festate%2Fdetail&url=https%3A%2F%2Fcom.example&_id=b7ca616466d6429e&rand=276822898&apiv=1&_idvc=8&_viewts=1718054103&_idts=1718027887&res=1290x2796&h=21&m=37&s=53&cookie=1&ua=iOS+17.5.1%2C+iPhone&lang=de_DE&country=DE&pv_id=YtxItI&cdt=2024-06-10T21%3A37%3A53.454787Z&token_auth=414698188cd1882e05089ceeb87a88a1"]}
```

This is the request.

**Comment by kuhnroyal** [comment]
The "country=DE" causes this. If I remove it, the request works in Postman.

**Comment by TesteurManiak** [comment]
It could be because the language code is not in lowercase, can you try with `country=de`.
If it is because of that we'll have to make a quick fix on the package.

**Comment by kuhnroyal** [comment]
lowercase doesn't change anything, I wonder if the `country` parameter only works with some plugin?

**Comment by kuhnroyal** [comment]
This is probably related to some auth problem on the backend side, the `country` parameter is only allowed when `token_auth` is actually on. I am sending a token but it doesn't seems to matter.
https://developer.matomo.org/api-reference/tracking-api#other-parameters-require-authentication-via-token_auth

**Comment by TesteurManiak** [comment]
Docs says that the token_auth can only be used with a super user or a user with write or admin permission.

> [...] the token_auth value of the Super User, or a user with write or admin permission to the website visits are being tracked for.

Maybe it is an issue with your user configuration.

**Comment by kuhnroyal** [comment]
Yeah, that is very likely. Let's assume that this is a backend problem on my side.

I think the library should still handle the error in this case. Check for the success code and verify that the tracked amount is equal to the batch size.
At least some logging should be provided if it doesn't match.

**Comment by TesteurManiak** [comment]
Yeah I think we should be able to implement such behavior 👍

**Comment by Johannes-Schiel** [comment]
Is there something new on this ? I have the same error on my app.

**Comment by TesteurManiak** [comment]
@Johannes-Schiel as said above, if your issue is related to the `country` query parameters, check if there's some configuration you have to do on your Matomo instance.

**Comment by Johannes-Schiel** [comment]
What kind of config do i have to update there ?

**Comment by TesteurManiak** [comment]
> What kind of config do i have to update there ?

https://github.com/Floating-Dartists/matomo-tracker/issues/155#issuecomment-2162181032

**Comment by lyio** [comment]
> Yeah, that is very likely. Let's assume that this is a backend problem on my side.
> 
> I think the library should still handle the error in this case. Check for the success code and verify that the tracked amount is equal to the batch size. At least some logging should be provided if it doesn't match.

Did anything ever happen to this suggestion? I.e. are there plans to handle when requests are invalid and not accepted by Matomo.

I have also noticed, that the plugin attaches the `token_auth` to the individual requests when doing a batch. The documentation has the request body looking like this, though: 
```json
{
   "requests": [
      "?idsite=1&url=https://example.org&action_name=Test bulk log Pageview&rec=1",
      "?idsite=1&url=https://example.net/test.htm&action_name=Another bulk page view&rec=1"
   ],
   "token_auth": "33dc3f2536d3025974cccb4b4d2d98f4"
}
```

Whereas the request body sent by the Plugin looks more like this:
```json
{
   "requests": [
      "?idsite=1&url=https://example.org&action_name=Test bulk log Pageview&rec=1&token_auth="33dc3f2536d3025974cccb4b4d2d98f4",
      "?idsite=1&url=https://example.net/test.htm&action_name=Another bulk page view&rec=1&token_auth="33dc3f2536d3025974cccb4b4d2d98f4"
   ],
   
}
```

**Comment by TesteurManiak** [comment]
> Did anything ever happen to this suggestion? I.e. are there plans to handle when requests are invalid and not accepted by Matomo.

Nothing has been worked on, you can open a separate issue dedicated to it if you feel like this is something that you might need.

> I have also noticed, that the plugin attaches the token_auth to the individual requests when doing a batch.

If I'm refering to Matomo's documentation, both ways seem to be supported, as we're only performing batch requests we could consider only using the `token_auth` field in the request.

<img width="867" height="159" alt="Image" src="https://github.com/user-attachments/assets/0c8d6737-9f71-4bac-bb07-1a0b147adae0" />
