### ISSUE TITLE
More Details about the device

### ISSUE THREAD

**Issue by Johannes-Schiel** [Floating-Dartists/matomo-tracker#163]
**Is your feature request related to a problem? Please describe.**

currently i only see something like "Model = Apple - iPhone" this is ok but it would be awesome when we get the real device name like "iPhone 14 Pro " or something like this.

**Describe the solution you'd like**

there are multiple flutter packages that generate those informations. I would use the https://github.com/Floating-Dartists/matomo-tracker/issues/163#issue-2367809935 for this i would create a feature like the platform_info 

**Describe alternatives you've considered**

**Additional context**

i would love to help create that feature if this is a solution :)

**Comment by TesteurManiak** [comment]
Was implemented in https://github.com/Floating-Dartists/matomo-tracker/pull/158
You can try it by pointing to the main branch or the latest commit on the repo.
