### ISSUE TITLE
support campaign tracking

### ISSUE THREAD

**Issue by nietsmmar** [Floating-Dartists/matomo-tracker#175]
**Describe the solution you'd like**
Is it possible to use campaign-tracking URL's with this package? I guess the package would need to read the URL parameters and forward them. I tried it and my test-campaign was not detected so I think it is not implemented yet?

**Comment by TesteurManiak** [comment]
It is implemented, you have a `campaign` property that you can set on all tracking methods. Maybe we're not sending the object properly. What have you tried? And which version of Matomo are you using?

**Comment by nietsmmar** [comment]
Ahh so I have to read the campaign property from the url myself and insert it into the campaign property. Thanks.
