### ISSUE TITLE
Posting a lot of duplicate actions

### ISSUE THREAD

**Issue by quadbyte** [Floating-Dartists/matomo-tracker#178]
**Describe the bug**
Package is posting a bunch of duplicates events.

**To Reproduce**
- Use my attached minimal flutter repro sample code.
- Launch the project. This shoot one trackEvent
- Go check in Matomo  Visitors/Realtime, and you will see events accumulating every 10 seconds.
- I usually get 6 to 10 duplicates and then it stop for a bit, sometimes it can post x50...  with the exact same timestamp and data.

**Expected behavior**
The package should post a event for every call to trackEvent()

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome
 - Version 130

**Additional context**
This is not a server issue, as we use the same Matomo instance with other languages (C#) and have zero issues.
[matomo_repro.zip](https://github.com/user-attachments/files/17414063/matomo_repro.zip)
![2024-10-17-102837_hyprshot](https://github.com/user-attachments/assets/13e560fe-7b6e-497b-a8f1-f1bd60882950)

**Comment by TesteurManiak** [comment]
Can you provide some of the logs you get with:
```dart
MatomoTracker.instance.initialize(verbosityLevel: Level.all);
```
When events are dequeued to be sent in a batch, there should be some logs with the length of the queue. This will help us to understand if it is because the event queue is not emptied properly.

**Comment by quadbyte** [comment]
Thanks for the reply.

Entries are never dequeued, due to  ClientException (ClientException: XMLHttpRequest error
Which is super odd, as there is no trace of error in the server's log (Running Matomo via nginx)

I'm suspecting some CORS sheenanigans.

`[Matomo] Processing queue 1
[Matomo]  -> {requests: [?idsite=46&rec=1&new_visit=1&ca=1&url=http%3A%2F%2Flocalhost%3A36953%2F&_id=4395e9a355184393&rand=23236901&apiv=1&res=1266x1290&h=16&m=7&s=13&cookie=1&ua=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F130.0.0.0+Safari%2F537.36&lang=en_GB&e_c=Main&e_a=Launched&cdt=2024-10-17T16%3A07%3A13.175Z]}
[Matomo]  <- ClientException: XMLHttpRequest error., uri=https://REDACTED.com/matomo.php
[Matomo] ClientException (ClientException: XMLHttpRequest error., uri=https://REDACTED.com/matomo.php)
[Matomo] Processing queue 1
`
