### ISSUE TITLE
Dependencies are very outdated

### ISSUE THREAD

**Issue by felix-barz-brickmakers** [Floating-Dartists/matomo-tracker#27]
Some of your dependencies are very out of date and need to be updated:

device_info_plus: 4.1.2 -> 7.0.1
package_info_plus: 1.4.3+1 -> 3.0.1

**Comment by felix-barz-brickmakers** [comment]
Recommendation: Enabled Dependabot for your repository so you get automatic pull requests for updates

**Comment by TesteurManiak** [comment]
Hi Felix, thanks for the suggestion, I've setup dependabot on the repo the dependencies should soon be updated to the latest and I'll release a new version on pub.dev soon.
