### ISSUE TITLE
Track duration in app

### ISSUE THREAD

**Issue by harrowmykel** [Floating-Dartists/matomo-tracker#30]
Hello, thanks for building this great plugin.
I wanted to ask if it is possible to track how long the user spent in the app or on a particular screen?
Are there plans to implement this?

Thanks again.

**Comment by TesteurManiak** [comment]
Matomo already support this out of the box, by sending events it will automatically calculate the time spend on a screen.

**Comment by harrowmykel** [comment]
Is there a specific type of event that I have to send?

**Comment by MeixDev** [comment]
It's all part of the official Matomo documentation.

"By default, Matomo will accurately track the time spent on all your pages, except the last page view of the visit, as Matomo counts the “Time spent on page” as 0 seconds by default."

Source: https://matomo.org/faq/how-to/faq_21824/

The knowledge database and the API reference of Matomo will usually answer most of your questions.

**Comment by harrowmykel** [comment]
Thanks a lot for the response. Just for other people looking for info. 

You have to use the Mixin to track the app use duration

use `TraceableClientMixin` or `TraceableWidget`
