### ISSUE TITLE
The request does not come to matomo

### ISSUE THREAD

**Issue by AlexMarg21** [Floating-Dartists/matomo-tracker#32]
Hello! We make a request to matomo using this SDK. The data has been sent successfully, but they do not come to matomo. Can you tell what we could have done wrong and what data you need to send to check it?

We using matomo version 4.10.1 and sdk version 1.7.0

**Comment by TesteurManiak** [comment]
Hi, please provide a minimal reproducible example of your issue. Note that this is not a SDK but merely a wrapper around the web API already provided by Matomo.

**Comment by AlexMarg21** [comment]
Sorry for the trouble, we figured it out ourselves. It was wrong destination server url (needed to specify /matomo.php at the end). Thank you.
