### ISSUE TITLE
queue in matomo.dart breaks tracking

### ISSUE THREAD

**Issue by timcreatedit** [Floating-Dartists/matomo-tracker#33]
**Describe the bug**
Events that get sent in the same `_dequeue()` loop get picked up by our Matomo instance incorrectly. This means that for example 3 quick consecutive screen views get tracked as the first view x 3 by Matomo.

**To Reproduce**
1. Send multiple events in rapid succession
2. Verify in Matomo console

**Additional context**
For now, we have resorted to a slightly hacky workaround of calling `dispatchEvents()` after each tracking call. We have tried to remove the Queue from matomo.dart altogether and it seems to work. Maybe someone could give us some context on why the Queue was implemented in the first place, because we would have a PR ready with the Queue removed that worked great in our testing.

**Comment by TesteurManiak** [comment]
Hi, as this package is a fork from @poitch's repository I don't know if the queue is especially needed, if you haven't experienced any issue/regression by removing it I'd be glad to see the change you've mentionned inside a PR 😄
