### ISSUE TITLE
Call to trackDimensions doesn't work as expected

### ISSUE THREAD

**Issue by adgeg** [Floating-Dartists/matomo-tracker#49]
Hi, 

Fist of all, thanks for your great job.

**Describe the bug**
When we call `trackDimensions()` method, the following calls to `trackEvent()`, `trackScreen()` etc… do not set dimensions, and we don't have any dimensions available in Matomo dashboard.

**To Reproduce**
1. Call `MatomoTracker.instance.trackDimensions({'dimension1' : 'value1'});`
2. Call `MatomoTracker.instance.trackScreen(context, eventName : 'screen1');`
3. With Flutter DevTools > Network, see the content of request to Matomo. Not any dimension query param is present.

**Expected behavior**
After a call to `trackDimensions`, dimensions should be usable in Matomo dashboard.

**Additional context**
Matomo tracker version : 2.0.0

**Comment by TesteurManiak** [comment]
Have you tried to track the dimension like this instead ?

```dart
MatomoTracker.instance.trackScreen(
  context,
  eventName : 'screen1',
  dimensions: {'dimension1' : 'value1'},
);
```

**Comment by adgeg** [comment]
Hello @TesteurManiak , it works the way you propose, and that's what we do now. But the comprehension of the method `trackDimensions` is misleading if we still need to  call dimensions parameter later in following `trackScreen/Event…`.
Furthermore, in the [pub.dev page of your library](https://pub.dev/packages/matomo_tracker), it is mentioned that it should work "at a visit level" if we call `trackDimensions`.
```

If you want to track Visit or Action dimensions you can either use the trackDimensions (if it's a Visit level dimension) or provide data in the optional dimensions param of trackEvent (if it's an Action level dimension):
```

**Comment by TesteurManiak** [comment]
Yeah you are right, I'll take a deeper look on this method, this feature was implemented by someone who is not a maintainer on the repo.

**Comment by petcupaula** [comment]
Hmm. And you have defined the dimension as a **visit level dimension** in Matomo?

I just tested on version 2.0.0 and seems to be sending fine the visit dimension using `trackDimension`, and for that matter also with `trackEvent`, in the `main.dart` of my flutter app. 

* Matomo request:
      <img width="293" alt="image" src="https://user-images.githubusercontent.com/12584735/218503159-2d1733fc-9510-4999-8879-fcfec7ce5e44.png"> 

* Matomo tracking the dimension:
      <img width="430" alt="image" src="https://user-images.githubusercontent.com/12584735/218503902-8f87355b-9b1f-42c8-ba3f-5f0420ae5f7f.png">

* Matomo Custom Dimensions setup:
      <img width="261" alt="image" src="https://user-images.githubusercontent.com/12584735/218504769-416127a3-bc14-4b9f-bd58-b2ac8f227db5.png">

**Comment by adgeg** [comment]
Hello @petcupaula, sorry I just see your message now.
Dimensions were properly set on our project for a very long time. Before using your library ,we made [a fork](https://github.com/BonnetM/dart-matomo/blob/main/lib/matomo.dart) of [dart-matomo](https://github.com/poitch/dart-matomo) to achieve dimensions. And it used to work perfectly fine.

We don't really use `trackEvent`, but for the `trackScreen` methods, when I inspect network requests, not any information about previously set dimensions are present. 

Now we use the `dimensions` parameter of the `track` methods, and it work as expected, even if we add to adjust in some way our calls:
```dart
void setDimensions(Map<String, String> dimensions) {
    _dimensions = dimensions.map((key, value) => MapEntry('dimension$key', Uri.encodeComponent(value)));
  }
```
