### ISSUE TITLE
Can't get tracking data 

### ISSUE THREAD

**Issue by Mrdogithub** [Floating-Dartists/matomo-tracker#50]
**Describe the bug**
Hi , guys

it's great job. thanks  for your contribution for this .

when i try to use "matomo-tracker" sdk  and can't not get the tracking data. i'm not sure what's the reason. 

my steps as below:

**To Reproduce**
1.download "matomo-tracker" example code 
2.update below code in main.dart file

=== example code 
  MyApp({Key? key}) : super(key: key) {
    Logger.root.level = Level.FINEST;
    Logger.root.onRecord.listen((LogRecord rec) {
      debugPrint(
        '[${rec.time}][${rec.level.name}][${rec.loggerName}] ${rec.message}',
      );
    });

    MatomoTracker.instance.initialize(
      siteId: 1,
      url: 'https://analytics.example.com/matomo.php',
    );
  }

=== my code after update 
  MyApp({Key? key}) : super(key: key) {
    Logger.root.level = Level.FINEST;
    Logger.root.onRecord.listen((LogRecord rec) {
      debugPrint(
        '[${rec.time}][${rec.level.name}][${rec.loggerName}] ${rec.message}',
      );
    });

    MatomoTracker.instance.initialize(
      siteId: 1,
      url: 'https://test2023.matomo.cloud/',
    );
  }

3.build example and generate apk packge, then upload third part platform . install in my android cell phone.

4.can't get any tracking data in this motomu server https://test2023.matomo.cloud/index.php

not sure what's the reason, please give some tips. 

Thank you.

**Comment by TesteurManiak** [comment]
To me it looks like your url isn't correct, based on[ matomo's documentation](https://developer.matomo.org/api-reference/tracking-api) your tracking HTTP API endpoint should end with `matomo.php`.

**Comment by Mrdogithub** [comment]
Thanks, it works!!

**Comment by Mrdogithub** [comment]
> To me it looks like your url isn't correct, based on[ matomo's documentation](https://developer.matomo.org/api-reference/tracking-api) your tracking HTTP API endpoint should end with `matomo.php`.

Thanks, it works!
