### ISSUE TITLE
Track users when the app is offline

### ISSUE THREAD

**Issue by mattjbrent** [Floating-Dartists/matomo-tracker#51]
Currently, when the mobile app is offline, tracking requests fail. Matomo native APIs fix this by queuing up tracking data and sending via the bulk API when the mobile app has connectivity as per [this link ](https://matomo.org/faq/general/will-matomo-track-users-when-the-web-app-or-mobile-app-is-offline-no-internet/)

Ideally, this would be implemented under the hood and happen automatically without additional configuration by the developer.

**Comment by TesteurManiak** [comment]
As we've already implemented a queuing mechanism it should be feasible. I'll try to take a look at it and make a prototype.
