### ISSUE TITLE
Cookieless mode

### ISSUE THREAD

**Issue by krifpvlic** [Floating-Dartists/matomo-tracker#53]
**Is your feature request related to a problem? Please describe.**
It seems as though this package doesn't support Matomo cookieless mode, which is useful if you want to track your users less or not show an analytics acceptance dialog. 

**Describe the solution you'd like**
Adding a "cookieless: true/false" option in MatomoTracker.instance.initialize which will not send or save first_visit and user_id

**Describe alternatives you've considered**
Setting a static userid (this still saves cookies)

**Comment by TesteurManiak** [comment]
I don't have any objection in adding such a feature but it might be for the best to first wait for the PR #54 to be merged so it'll be easier to interact with the shared preferences.
