### ISSUE TITLE
I am experiencing a 403 error when sending tracking data to my Matomo server using the matomo_tracker package in my Flutter app

### ISSUE THREAD

**Issue by devzhr** [Floating-Dartists/matomo-tracker#56]
**Describe the bug**
I am experiencing a 403 error when sending tracking data to my Matomo server using the matomo_tracker package in my Flutter app. The same URL works fine when used in native apps (Swift).

**To Reproduce**
1. Create a new Flutter app and add the matomo_tracker package as a dependency
2. Configure the MatomoTracker with the following settings:
    ```dart
    MatomoTracker.instance.initialize(
      siteId: 6,
      url: 'https://matomo.exemple.com/piwik.php',
   );
   ```
3. The server responds with a 403 error.

**Expected behavior**
The tracking data should be sent successfully to the Matomo server without a 403 error.

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - OS: iOS16.2

**Additional context**
The same Matomo URL works fine in native apps (Swift).
I have already checked the Matomo server settings, site ID, and token authorization, but the issue persists.

Please let me know if there's any known issue or solution for this problem.

**Comment by TesteurManiak** [comment]
Can you provide the cURL of the failing request ?

**Comment by devzhr** [comment]
Thank you Maniak for your answer

the same request works with postman and not with flutter i used 2.0.0 i tried both `piwik.php` and `matomo.php`

**Comment by TesteurManiak** [comment]
Ok but can you provide the cURL of the failing request (you can find in the [network tab of the dart devtools](https://docs.flutter.dev/development/tools/devtools/network)). This will help to identify what might be going wrong with the request sent from the package.

**Comment by 4gmayank** [comment]
You may use
MatomoTracker.instance.initialize(
  siteId: 6,
  url: 'https://myhost.matomo.cloud/matomo.php',
);
