### ISSUE TITLE
URLs have double slashs in dashboard

### ISSUE THREAD

**Issue by EPNW-Eric** [Floating-Dartists/matomo-tracker#64]
According to the examples, a traceable path already contains a leading '/', e.g.:
https://github.com/Floating-Dartists/matomo-tracker/blob/2dbf25209c995762daf6461cbcfa5ca0952798ef/lib/src/traceable_widget_mixin.dart#L25-L29
so I think it is reduntant to add one when constructing the url in
https://github.com/Floating-Dartists/matomo-tracker/blob/2dbf25209c995762daf6461cbcfa5ca0952798ef/lib/src/matomo_event.dart#L113
because this leads to the Matomo dashboard having entries like `http://example.org//home` (notice the double slash).

Maybe we could do something like this instead:
```dart
String _combineBaseAndPath(String contentBase, String? path){
  if(path==null){
    return contentBase;
  }
  final addSlash=path.startsWith('/') ? '' : '/';
  return '$contentBase$addSlash$path';
}
```
This would ensure backwards compatibility if someone noticed that and declarded their path without leading `/` but would allow new implementations to make the leading `/` part of the path (as in `/home`), since in http, the slash is actually part of the path. 

I have currently no insights on how many people would be affected if not doing such a check and just use `$contentBase$path`... Would you consider such a change a breaking change?

**Comment by AshwanthramKL** [comment]
I'd like to work on this.

**Comment by TesteurManiak** [comment]
@AshwanthramKL sure, I've assigned you
