### ISSUE TITLE
Unused parameters in TraceableClientMixin and trackScreenWithName

### ISSUE THREAD

**Issue by EPNW-Eric** [Floating-Dartists/matomo-tracker#65]
The [`TraceableClientMixin`](https://pub.dev/documentation/matomo_tracker/3.0.0/matomo_tracker/TraceableClientMixin-mixin.html) is just convenience for calling [`trackScreenWithName`](https://pub.dev/documentation/matomo_tracker/3.0.0/matomo_tracker/MatomoTracker/trackScreenWithName.html), which means that every mixin field corresponds with a method parameter. Since thie package uses the [Tracking HTTP API](https://developer.matomo.org/api-reference/tracking-api), every method parameter in `trackScreenWithName` corresponds with a Tracking HTTP API url parameter.

The following table shows these relations:
| TraceableClientMixin | trackScreenWithName | Tracking HTTP API |
|----------------------|---------------------|-------------------|
| `traceName`          | `widgetName`        | `action_name`     |
| `traceTitle`         | `eventName`         | `e_n`             |
| `path`               | `path`              | `url`*            |
| `widgetId`           | `currentScreenId`   | `pv_id`           |

*: Note that to construct `url`, `path` is appended to [`MatomoTracker.contentBase`](https://pub.dev/documentation/matomo_tracker/3.0.0/matomo_tracker/MatomoTracker/contentBase.html).

What I now do not understand is `traceTitle`, `eventName` and ultimately `e_n`, because from my I understanding of the Tracking HTTP Api, the `e_n` parameter is not used here by Matomo; it is only used when tracking events, which also *requires* the `e_c` and `e_a` url parameters to be present.

Furthermore the [JavaScript Tracking Client](https://developer.matomo.org/api-reference/tracking-javascript) also only knows one parameter for it's `trackPageView()` method (which I believe is their equivalent of `trackScreenWithName`?): `customTitle`, which is then later used as `action_name`:
https://github.com/matomo-org/matomo/blob/b41f574dd842b3a565b46956380284f1d119192a/js/piwik.js#L4170-L4175

After creating a test project, I was also not able to locate the string I set `traceTitle` to anywhere in the Matomo dashboard.

This brings me to the conclusion that `traceTitle` and `eventName` are unused. Is there anything I am missing?

**Comment by EPNW-Eric** [comment]
Another thing I noticed just now is that while `trackScreenWithName` has an optional `dimensions` parameter, the `TraceableClientMixin` does not have a `dimensions` field. I think it would be great to have one to highlight the connection between `trackScreenWithName` and `TraceableClientMixin`.

**Comment by TesteurManiak** [comment]
Thanks for the issue I'm going to investigate the unused parameters and might also uniformize the namings for better clarity. (Note that it might make some comments you've added in #63 not needed anymore afterwards)
