### ISSUE TITLE
Issues on visit & user id logs

### ISSUE THREAD

**Issue by ThomasEcalle** [Floating-Dartists/matomo-tracker#75]
Hi !

First of all, thank you for maintaining this package :)

I am quite new in matomo so I would like to apologize if missunderstood some concepts.
I have tried it in a very easy way by initializing the package and then logging some events or screens.

Events & Screens logging work very well but I don't understand how the visits count and the user ID work and I think their might have a bug:

Event if I open & close many times the app, all the events & the screens are logged in the same Visit with the same Visitor ID.

Correct me if I am wrong but, as I understood the package (and as other analytics package work):

- if a user ID is not set by `setVisitorUserId()` then a different user ID should be generated each time (like "anonymous" users)
- each time I open the app (if it was closed), it should be logged as a new visit in the dashboard.

The app is pretty easy (it is just a little app to test matomo) and has only some initialisation: 

```
void main() async {
  await MatomoTracker.instance.initialize(
      siteId: 42,
      url: 'my_url',
    );

   runApp(...);
}
```

And then some events logging:

```
MatomoTracker.instance.trackEvent(
      eventCategory: category,
      action: action,
      eventName: name,
      eventValue: value,
    );
```

Thank you in advance for your help.

**Comment by ThomasEcalle** [comment]
Ok, my bad, I didn't read the code and I think I understand a bit better.

As I can see in the code, we are saving in shared preferences the generated User ID from one "session" to an other to be able to reuse it.
Same thing with visits count that is saved in shared preferences.

I also had a look into the official API (https://developer.matomo.org/api-reference/tracking-api) and saw this:

```
If a visit is found in the last 30 minutes with your specified User ID, then the new action will be recorded to this existing visit.
```

So.... what I understand is that, even if we are logging a new visit count each time, the API will look at the last visit and, if it was less than 30 minutes ago... will log the new events in the same visit, even if we log a new visit count.

I have tested everything after 30 minutes and I can confirm that it works that way.

But I still don't understand why, to be honest.

* What is the point of this 30 minutes rule ? If I log events every 25 minutes, I could have only ONE visit whereas I have maybe opened / closed the app hundred times, that is quite strange

* Shouldn't we choose if we want the visitor ID to be saved in shared preferences ?
If a user is not logged in, we could assume that every app instance is actually lunched by anonymous user and not always the same

Actually, why are the visits count and user ID not handled by the API ?
Shouldn't the API be the only one responsible for this logic ? 
What would happen if I have both an Android & an iOS app (native) and one package use this saving user id method and the other one don't ?

Once again, so sorry for calling it a "Bug", that was obviously a missunderstanding.

I also may be asking all my questions to the wrong person and do not hesitate to tell me if it is the case

**Comment by TesteurManiak** [comment]
Hi @ThomasEcalle,

> What is the point of this 30 minutes rule ? If I log events every 25 minutes, I could have only ONE visit whereas I have maybe opened / closed the app hundred times, that is quite strange

> Actually, why are the visits count and user ID not handled by the API ?

We are not affiliated to the Matomo development team so I cannot say for sure why this behavior is in place on the API side. On another note we are actually keeping the visit count locally in the shared preferences and sending it with the `_idvc` query parameter to the API, [but it has been removed in Matomo 4](https://github.com/matomo-org/matomo/issues/17178) (We should probably remove the code related to this btw)
Seems like there is nothing more we can do on our end.

> Shouldn't we choose if we want the visitor ID to be saved in shared preferences ?
> If a user is not logged in, we could assume that every app instance is actually lunched by anonymous user and not always the same

This should be doable by modifying a bit the "cookieless" behavior already implemented. For now, you can only specify the `cookieless` property in the `initialize` method, but by allowing to change it on the fly I think you might be able to obtain the result you are looking for.

If it's something you'd like to see in this package I invite you to open a feature request with some details to understand exactly what is your need and how the package should be solving it.

**Comment by EPNW-Eric** [comment]
The idea behind the 30min thing is that matomo was developed for web usage. Where in the app world we know when a user closes or leaves the app, in the web world there is no such concept as "session".

For the app usage it would be helpfull to actually be aware of app closes and initiate new visits. The tracking API knows a parameter for that: `new_visit`. To fix the behaviour we could always set the `new_visit` parameter for the first event that is dispatched. I'd be happy to come up with something.

**Comment by TesteurManiak** [comment]
Thanks for the insights @EPNW-Eric!
Yeah, the `new_visit` param seems to be the way to go, feel free to open a PR, otherwise I can also work on this 👍
