### ISSUE TITLE
HTTP 400 Bad Request on the example

### ISSUE THREAD

**Issue by tilonet** [Floating-Dartists/matomo-tracker#8]
I have running the Matomo Backend via Docker  https://github.com/matomo-org/docker the nginx example, Matomo Version 4.9.1

If I connect your example App with this Backend I get a HTTP 400 

exemple call: http://localhost:8080/matomo.php?idsite=1&rec=1&action_name=Created+HomePage&url=https%3A%2F%2Fcom.example.example&_id=cf0cd7af39194e79&rand=307316931&apiv=1&_idvc=12&_viewts=1653736918&_idts=1653721097&res=1440x3064&h=11&m=21&s=58&cookie=1&ua=Android+12+%28SDK+32%29%2C+Google+Pixel+6+Pro&lang=de_DE&country=DE

I found out that the country=DE cause the Problem without this country it works fine

**Comment by M123-dev** [comment]
Sorry this goes on me @tilonet, I've proposed a fix in #10
