### ISSUE TITLE
Build problem with package_info_plus and device_info_plus dependencies

### ISSUE THREAD

**Issue by scolnet** [Floating-Dartists/matomo-tracker#80]
Hi team,

Could you update dependencies ?
package_info_plus: ^4.0.0
device_info_plus: ^9.0.0

**Comment by TesteurManiak** [comment]
Hi,
Those dependencies have already been updated on the [dev branch](https://github.com/Floating-Dartists/matomo-tracker/tree/dev).
We will make a dev release for the v5 on pub.dev soon. For now you can target the dev branch in your `pubspec.yaml`.
