### ISSUE TITLE
Events not shown in the Backend

### ISSUE THREAD

**Issue by tilonet** [Floating-Dartists/matomo-tracker#9]
I have running the Matomo Backend via Docker https://github.com/matomo-org/docker the nginx example, Matomo Version 4.9.1

example call: http://localhost:8080/matomo.php?idsite=1&rec=1&url=https%3A%2F%2Fcom.example.example&_id=cf0cd7af39194e79&rand=822786072&apiv=1&_idvc=12&_viewts=1653736918&_idts=1653721097&res=1440x3064&h=11&m=22&s=1&cookie=1&ua=Android+12+%28SDK+32%29%2C+Google+Pixel+6+Pro&lang=de_DE&uid=cf0cd7af39194e79&pv_id=zhO56F&e_a=Click&e_n=IncrementCounter

The API Call are received in the Backend but I cant see the Increment Counter event

**Comment by tilonet** [comment]
Please help me with with the Issue, I really want to use this tracker.  Maybe the screenshots can clarify my problem. The link above have the result shown on the screenshot. The events are tracked but I cant see which one, there is no label "Increment Counter" on dashboard and the event page under Behaviour is empty

![Bildschirmfoto 2022-06-09 um 07 49 17](https://user-images.githubusercontent.com/25120666/172774177-7a6bcc38-5327-4656-b86f-f21c98f9f3bd.png)
creenshots

**Comment by M123-dev** [comment]
Can reproduce this as well @tilonet having a look if I can figure out what causes the problem
