### ISSUE TITLE
Update LICENSE

### ISSUE THREAD

**Issue by EPNW-Eric** [Floating-Dartists/matomo-tracker#95]
The current LICENSE file dates back to 2020. It might be a good idea to update the license file to reflect all contributors. [This](https://law.stackexchange.com/questions/16847/how-should-multiple-copyright-holders-be-credited-using-the-mit-license) could be interesting input.

**Comment by MeixDev** [comment]
Hello!

After discussing it a bit with @TesteurManiak ; we came to the conclusion that a new line should be added under Jérôme's copyrights for the contributors to this current repository.

The idea would be to add all "major" contributors, currently stated to be those with 3 or more pull requests (or a rich one, this doesn't have to be a clear requirement).

Currently, this would include @TesteurManiak ; @Pierre-Monier ; myself ; @M123-dev and you @EPNW-Eric !

I'll open a Pull Request to complete this.

**Comment by MeixDev** [comment]
Given this is merged on the dev branch, and I see approval in the form of thumbs up from both Marvin and Eric, I'll close this !
