### ISSUE TITLE
Updating the http dependency

### ISSUE THREAD

**Issue by tuotau-lessonapp** [Floating-Dartists/matomo-tracker#98]
Hi!

If possible, could the http dependency be updated from ^0.13.5 to ^1.0.0 for the next release?
Thanks!

**Comment by TesteurManiak** [comment]
Sure, I'll update the dependency for the dev version and it'll be part of the next major release.

**Comment by TesteurManiak** [comment]
Available in pre-release on [v4.0.0-dev.2](https://pub.dev/packages/matomo_tracker/versions/4.0.0-dev.2)
